image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - emacs-nox
environment:
  site: knarkzel.srht.site
tasks:
- package: |
    cd $site
    ./build.sh
    cd public/
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz
