#+TITLE: Apuss Dialogue

#+begin_quote
Me: The sun setting is so beautiful 

AP:  The sun doesn't set, it doesn't move downward

Me: I'm not thinking straight, I need to clear my head

AP: You can't think in a physical direction, and you can't clear your head, you will die. 

Me: She broke my heart

AP: How are you still alive then?

Me: I remember starting school like it was yesterday, time flies so fast

AP: Time doesn't fly, this is a scientific mistake

Me: My team lost the game, I can't believe this!!

AP: To acknowledge that your team lost, entails that you believe that you team lost, so you actually do believe that your team lost the game. You contradicted yourself, fool

Me: AP is a clown

AP: I'm actually not employed as a clown, I'm unemployed

Me: I will not tell anyone your secret, I give you my word

AP: You can't give people words

Me: Ridvan, farid already refuted you a million times, why don't you respond?

AP: Farid only refuted me 52 times, not a million times, thus, you are factually incorrect

Me: My suitcase weighs a ton!

AP: No it only weights 50kg, you are wrong again

Me: Thanks for speaking with me

AP: This was irrelevant
#+end_quote
