#+title: British colonization of Egypt and Modernity

Quote from anonymous:

#+begin_export html
<blockquote>
#+end_export
To understand the liberal secularist and feminist project in the Muslim
world, one needs to revisit the British colonization of Egypt.

Everlyn Baring, better known as Lord Cromer, was the British Proconsul-General
in occupied Egypt between 1877 and 1907. He wrote about his tenure in his
book "Modern Egypt" (1916). Here are some conclusions from his book:

*** The West will not tolerate an Islamic government

On page 565, he said that it would be "absurd" to assume that Europe would
tolerate a "government based on purely Mohammedan principles and obsolete
Oriental ideas."

*** Muslims must be forced to adopt the principles of Western civilization

On page 538, he said that Egypt had to be "forced into imbibing the true
spirit of Western civilization."

*** Westernization must be introduced under the guise of women's rights.

Lord Cromer says that the "position of women" in Muslim countries was a
"fatal obstacle" in the introduction of colonial values. (page 539)

*** The West must educate a class of young secular Muslims to be the rulers

Cromer's hope was that a Europeanized education system would cause an Egyptian
to "lose his Islamism", cause him to "no longer believe that he is always
in the presence of his Creator", and only hang onto "the least worthy portions
of his nominal religion" for the sake of convenience. (page 230)

*** The West must reform Islam.

Cromer says that the goal should be to create "de-moslemized Moslems",
where people are Muslims-by-name, but in actuality, are "agnostic". After
all, Cromer says, "Islam cannot be reformed ... reformed Islam is Islam
no longer." (pages 228-229)

*** The Muslim reformer would hate Muslim scholarship more than Europeans do.

The Westernized Muslim would consider the `alim to be a "social derelict",
use him in matters of convenience, but otherwise disrespect him. On the
other hand, a European Christian intellectual would at least look at the
`alim with sympathy and respect, as a "representative of an ancient faith".
(page 299-30)

*** Modernized Muslims will become Deists.

"It is conceivable that, as time goes on, the Moslems will develop a religion,
possibly a pure Deism, which will not be altogether the Islamism of the
past and of the present, and which will cast aside much of the teaching
of Mohammed, but which will establish a moral code sufficient to hold society
together by bonds other than those of unalloyed self-interest." (page 234)

We can see therefore that Islamic reform started as a colonial project.
A project that has been devilishly designed by European intellectuals to
undermine the clerics, introduce secular humanist institutions, and gradually
and inconspicuously lead Muslims away from the central tenets of their
tradition. They knew that this reformed, liberal Muslim would not be a
Muslim at all, but just a Europeanized invertebrate (i.e. a spineless being)
who would maneuver the religion to his needs.

This seven-step process is exactly what is happening to Muslim youth in
the West. They volunteer themselves to Western academia and pop culture,
and are led away from a truly Islamic worldview and epistemology. And while
they fool themselves into calling themselves "Muslim reformers", or "Muslim
feminists", or "moderate Muslims", or "liberal Muslims", their puppet masters
know that these are all contradictions in terms.
