name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    container:
        image: alpine/git

    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs
        run: apk add emacs-nox

      - name: Install highlight
        run: apk add highlight

      - name: Install rsync
        run: apk add rsync

      - name: Test 1
        run: pwd
        
      - name: Test 2
        run: ls

      - name: Build the site
        run: ./build.sh

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public